version: 3
tasks:
  default:
    cmds:
      - task: run

  run:race:
    desc: "run confirm with race detection"
    dir: "{{.USER_WORKING_DIR}}" # allow user to pass relative paths as arguments
    cmds:
      - go run -race 'github.com/romnn/confirm' {{.CLI_ARGS}}

  run:
    desc: "run confirm"
    interactive: true
    dir: "{{.USER_WORKING_DIR}}" # allow user to pass relative paths as arguments
    cmds:
      - go run 'github.com/romnn/confirm' {{.CLI_ARGS}}

  build:race:
    desc: "build confirm with race detection"
    cmds:
      - go build -race 'github.com/romnn/confirm' {{.CLI_ARGS}}

  build:
    desc: "build confirm"
    cmds:
      - go build ./... {{.CLI_ARGS}}

  build:executable:
    desc: "build confirm executable"
    aliases: ["build:binary"]
    cmds:
      - go build 'github.com/romnn/confirm' {{.CLI_ARGS}}

  build:goreleaser:
    desc: "build confirm in release mode using goreleaser"
    cmds:
      - goreleaser build --snapshot --clean

  release:
    desc: "release confirm using goreleaser"
    cmds:
      - goreleaser release --clean

  tidy:
    desc: "tidy golang modules"
    aliases: [install]
    cmds:
      - go get ./...
      - go mod tidy

  update:
    desc: "update golang dependencies"
    cmds:
      - go get -u ./...
      - task: tidy

  typos:
    desc: "spell check source files"
    aliases: [spellcheck]
    cmds:
      - typos

  format:
    desc: "format sources"
    cmds:
      - golines -m 88 -t 4 -w ./ {{.CLI_ARGS}}

  lint:
    desc: "lint"
    aliases: [check]
    cmds:
      - go vet ./... {{.CLI_ARGS}}
      - staticcheck ./... {{.CLI_ARGS}}
      - golangci-lint run ./... {{.CLI_ARGS}}

  test:
    desc: "test with race detection"
    aliases: ["test:race"]
    cmds:
      - richgo test ./... -race {{.CLI_ARGS}}
